### ISSUE TITLE
Cannot exec googkit setup on Python 2.6.8

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#3]
Cannot exec `googkit setup` on Python 2.6.8.

Error message is:

```
Downloading Closure Library...
Cloning into 'closure/library'...
remote: Counting objects: 44923, done.
Receiving objects: 100% (44923/44923), 18.10 MiB | 2.10 MiB/s, done.
Resolving deltas: 100% (35938/35938), done.
Downloading Closure Compiler...
Traceback (most recent call last):
  File "/usr/local/googkit/bin/../googkit.py", line 64, in <module>
    command.run()
  File "/usr/local/googkit/commands/setup.py", line 57, in run
    self.setup_closure_compiler()
  File "/usr/local/googkit/commands/setup.py", line 44, in setup_closure_compiler
    lib.unzip.run(compiler_zip, compiler_root)
  File "/usr/local/googkit/lib/unzip.py", line 8, in run
    with zipfile.ZipFile(zip_path) as z:
AttributeError: ZipFile instance has no attribute '__exit__'
```

**Comment by cocopon** [comment]
It seems to be a bug of Python. hmm...
http://bugs.python.org/issue5511

**Comment by Kuniwak** [comment]
OK, I abandon old pythons support.
Thanks @cocopon !
