### ISSUE TITLE
11 tests failed on Windows7

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#30]
11 tests were failed on Windows7.

```
C:\googkit>python --version
Python 3.3.2

C:\googkit>python -m unittest discover
.F.F..FF........................................................................
..............E.FE.EE.FF.E..FFF.F......
======================================================================
ERROR: test_default_config (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 127, in test_default_config
    self.assertEqual(googkit.lib.path.default_config(), '/dummy/usr/local/googki
t/etc/default.cfg')
  File "C:\googkit\googkit\lib\path.py", line 62, in default_config
    raise GoogkitError(msg)
googkit.lib.error.GoogkitError: Default config file is not found: /dummy/usr/loc
al/googkit\etc\default.cfg

======================================================================
ERROR: test_plugin (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 156, in test_plugin
    self.assertEqual(googkit.lib.path.plugin(), '/dummy/usr/local/googkit/googki
t/plugins')
  File "C:\googkit\googkit\lib\path.py", line 71, in plugin
    raise GoogkitError(msg)
googkit.lib.error.GoogkitError: Plugins directory is not found: /dummy/usr/local
/googkit\googkit\plugins

======================================================================
ERROR: test_project_config_on_current (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 78, in test_project_config_on_cu
rrent
    googkit.lib.path.project_config('/dir1/dir2/dir3/dir4'),
  File "C:\googkit\googkit\lib\path.py", line 41, in project_config
    raise GoogkitError('Project directory is not found.')
googkit.lib.error.GoogkitError: Project directory is not found.

======================================================================
ERROR: test_project_config_on_groundchild (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 60, in test_project_config_on_gr
oundchild
    googkit.lib.path.project_config('/dir1/dir2/dir3/dir4'),
  File "C:\googkit\googkit\lib\path.py", line 41, in project_config
    raise GoogkitError('Project directory is not found.')
googkit.lib.error.GoogkitError: Project directory is not found.

======================================================================
ERROR: test_template (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 170, in test_template
    self.assertEqual(googkit.lib.path.template(), '/dummy/usr/local/googkit/etc/
template')
  File "C:\googkit\googkit\lib\path.py", line 80, in template
    raise GoogkitError(msg)
googkit.lib.error.GoogkitError: Template directory is not found: /dummy/usr/loca
l/googkit\etc\template

======================================================================
FAIL: test_apply_config_all (test.commands.test_apply_config.TestApplyConfigComm
and)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\commands\test_apply_config.py", line 131, in test_apply_
config_all
    self.cmd.apply_config.assert_any_call(expected_call)
  File "C:\Python33\lib\unittest\mock.py", line 782, in assert_any_call
    '%s call not found' % expected_string
AssertionError: mock('C:\\googkit\\test\\fixture\\stub_project\\development\\js_
dev/example.js') call not found

======================================================================
FAIL: test_multitestrunner_css (test.commands.test_apply_config.TestApplyConfigC
ommand)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\commands\test_apply_config.py", line 46, in test_multite
strunner_css
    self.assertEqual(self.cmd.update_multitestrunner_css(line, StubConfig.DEVELO
PMENT_DIR), expected)
AssertionError: '<link rel="stylesheet" type="text/css" href="../../CLOSURE/LIBR
ARY/CLOSURE/CSS/ [truncated]... != '<link rel="stylesheet" type="text/css" href=
"..\\..\\CLOSURE\\LIBRARY\\CLOSURE\ [truncated]...
- <link rel="stylesheet" type="text/css" href="../../CLOSURE/LIBRARY/CLOSURE/CSS
/MULTITESTRUNNER.CSS">
?                                                ^  ^       ^       ^       ^
^
+ <link rel="stylesheet" type="text/css" href="..\..\CLOSURE\LIBRARY\CLOSURE\CSS
\MULTITESTRUNNER.CSS">
?                                                ^  ^       ^       ^       ^
^


======================================================================
FAIL: test_update_base_js (test.commands.test_apply_config.TestApplyConfigComman
d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\commands\test_apply_config.py", line 32, in test_update_
base_js
    self.assertEqual(self.cmd.update_base_js(line, StubConfig.DEVELOPMENT_DIR),
expected)
AssertionError: '<script type="text/javascript" src="../../CLOSURE/LIBRARY/CLOSU
RE/GOOG/BASE.JS" [truncated]... != '<script type="text/javascript" src="..\\..\\
CLOSURE\\LIBRARY\\CLOSURE\\GOOG\\BA [truncated]...
- <script type="text/javascript" src="../../CLOSURE/LIBRARY/CLOSURE/GOOG/BASE.JS
"></script>
?                                       ^  ^       ^       ^       ^    ^
+ <script type="text/javascript" src="..\..\CLOSURE\LIBRARY\CLOSURE\GOOG\BASE.JS
"></script>
?                                       ^  ^       ^       ^       ^    ^


======================================================================
FAIL: test_update_deps_js (test.commands.test_apply_config.TestApplyConfigComman
d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\commands\test_apply_config.py", line 39, in test_update_
deps_js
    self.assertEqual(self.cmd.update_deps_js(line, StubConfig.DEVELOPMENT_DIR),
expected)
AssertionError: '<script type="text/javascript" src="JS_DEV/DEPS.JS"></script>'
!= '<script type="text/javascript" src="JS_DEV\\DEPS.JS"></script>'
- <script type="text/javascript" src="JS_DEV/DEPS.JS"></script>
?                                           ^
+ <script type="text/javascript" src="JS_DEV\DEPS.JS"></script>
?                                           ^


======================================================================
FAIL: test_googkit_root (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 148, in test_googkit_root
    self.assertEqual(googkit.lib.path.googkit_root(), '/dummy/googkit')
AssertionError: 'C:\\dummy\\googkit' != '/dummy/googkit'
- C:\dummy\googkit
? ^^^     ^
+ /dummy/googkit
? ^     ^


======================================================================
FAIL: test_project_root_on_current (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 39, in test_project_root_on_curr
ent
    '/dir1/dir2/dir3/dir4')
AssertionError: None != '/dir1/dir2/dir3/dir4'

======================================================================
FAIL: test_project_root_on_grandchild (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 27, in test_project_root_on_gran
dchild
    '/dir1/dir2')
AssertionError: None != '/dir1/dir2'

======================================================================
FAIL: test_user_config_on_groundchild (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 93, in test_user_config_on_groun
dchild
    self.assertEqual(googkit.lib.path.user_config(), '/home/user/.googkit')
AssertionError: '/home/user\\.googkit' != '/home/user/.googkit'
- /home/user\.googkit
?           ^
+ /home/user/.googkit
?           ^


======================================================================
FAIL: test_user_config_with_file_missing (test.lib.test_path.TestPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_path.py", line 110, in test_user_config_with_fi
le_missing
    self.assertEqual(googkit.lib.path.user_config(), '/home/user/.googkit')
AssertionError: None != '/home/user/.googkit'

======================================================================
FAIL: test_load_with_invalid_plugin (test.lib.test_plugin.TestPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_plugin.py", line 110, in test_load_with_invalid
_plugin
    googkit.lib.plugin.load(mock_tree)
AssertionError: GoogkitError not raised

======================================================================
FAIL: test_load_with_two_plugins (test.lib.test_plugin.TestPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\googkit\test\lib\test_plugin.py", line 54, in test_load_with_two_plug
ins
    mock_import.assert_any_call('plugins.dummy1.command', fromlist=['command'])
  File "C:\Python33\lib\unittest\mock.py", line 782, in assert_any_call
    '%s call not found' % expected_string
AssertionError: __import__('plugins.dummy1.command', fromlist=['command']) call
not found

----------------------------------------------------------------------
Ran 119 tests in 0.111s

FAILED (failures=11, errors=5)
```

**Comment by cocopon** [comment]
Can you fix it?
I don't have Windows...

**Comment by Kuniwak** [comment]
I'm trying to fix this.

**Comment by cocopon** [comment]
Thanks a lot, ready for 0.1.0! :sunglasses:
