### ISSUE TITLE
googkit not works on Windows

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#37]
```
C:\Users\###\Desktop\test>googkit setup
Downloading Closure Library...
Traceback (most recent call last):
  File "C:\Python33\lib\subprocess.py", line 1106, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\Scripts\googkit-script.py", line 9, in <module>
    load_entry_point('googkit==0.1.0', 'console_scripts', 'googkit')()
  File "C:\Python33\lib\site-packages\googkit\__init__.py", line 41, in main
    command.run()
  File "C:\Python33\lib\site-packages\googkit\commands\sequence.py", line 15, in
 run
    command.run()
  File "C:\Python33\lib\site-packages\googkit\commands\command.py", line 54, in
run
    self.run_internal()
  File "C:\Python33\lib\site-packages\googkit\commands\download.py", line 56, in
 run_internal
    self.download_closure_library()
  File "C:\Python33\lib\site-packages\googkit\commands\download.py", line 26, in
 download_closure_library
    googkit.lib.clone.run(library_repos, library_root)
  File "C:\Python33\lib\site-packages\googkit\lib\clone.py", line 11, in run
    _clone(repos, target_path)
  File "C:\Python33\lib\site-packages\googkit\lib\clone.py", line 34, in _clone
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE
)
  File "C:\Python33\lib\subprocess.py", line 820, in __init__
    restore_signals, start_new_session)
  File "C:\Python33\lib\subprocess.py", line 1112, in _execute_child
    raise WindowsError(*e.args)
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
```

**Comment by cocopon** [comment]
Related: http://stackoverflow.com/questions/4965175/make-subprocess-find-git-executable-on-windows
