### ISSUE TITLE
googkit do not works on OSX Mavericks

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#39]
```
$ googkit build --verbose
Building for debug...
[Error] Compilation failed:
closure/library/closure/bin/build/closurebuilder.py: Scanning paths...
closure/library/closure/bin/build/closurebuilder.py: 936 sources scanned.
closure/library/closure/bin/build/closurebuilder.py: Building dependency tree..
Traceback (most recent call last):
  File "closure/library/closure/bin/build/closurebuilder.py", line 262, in <module>
    main()
  File "closure/library/closure/bin/build/closurebuilder.py", line 251, in main
    compiler_flags=options.compiler_flags)
  File "/Users/###/compiler.py", line 125, in Compile
    java_version = _ParseJavaVersion(_GetJavaVersionString())
  File "/Users/###/compiler.py", line 37, in _GetJavaVersionString
    return subprocess.check_output(['java', '-version'], stderr=subprocess.STDOUT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['java', '-version']' returned non-zero exit status 1
```

**Comment by Kuniwak** [comment]
Install [Java SE6](http://www.oracle.com/technetwork/java/javase/downloads/index.html).
