### ISSUE TITLE
My googkit.build is failure in Python3.4.2

### ISSUE THREAD

**Issue by kubo39** [googkit/googkit#60]
```
$ googkit build
Traceback (most recent call last):
  File "/Users/hoge/googkit/bin/../googkit.py", line 5, in <module>
    googkit.main()
  File "/Users/hoge/googkit/googkit/__init__.py", line 46, in main
    command.run()
  File "/Users/hoge/googkit/googkit/commands/command.py", line 72, in run
    self.run_internal()
  File "/Users/hoge/googkit/googkit/commands/build.py", line 312, in run_internal
    self.build_production(html_path, project_root, should_clean)
  File "/Users/hoge/googkit/googkit/commands/build.py", line 220, in build_production
    self.setup_files(config.production_dir(), should_clean)
  File "/Users/hoge/googkit/googkit/commands/build.py", line 114, in setup_files
    self.compile_resource(html_path)
  File "/Users/hoge/googkit/googkit/commands/build.py", line 135, in compile_resource
    self.compiled_js_path(html_path), os.path.dirname(html_path))
  File "/Users/hoge/googkit/googkit/commands/build.py", line 156, in compiled_js_path
    ext_pattern = self.config.compiled_js_ext()
  File "/Users/hoge/googkit/googkit/lib/config.py", line 58, in compiled_js_ext
    return self.parser.get('project', 'compiled_js_ext')
  File "/Users/hoge/.pyenv/versions/3.4.2/lib/python3.4/configparser.py", line 773, in get
    d)
  File "/Users/hoge/.pyenv/versions/3.4.2/lib/python3.4/configparser.py", line 374, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/Users/hoge/.pyenv/versions/3.4.2/lib/python3.4/configparser.py", line 423, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%s.min.js'
```

My Environment:
- Mac OSX: Darwin Kernel Version 13.4.0 x86_64

**Comment by Kuniwak** [comment]
Thanks your reporting.

I try to `googkit build` on python 3.4.1, and I get the same error.

**Comment by Kuniwak** [comment]
Hmm, it seems ConfigParser problem.
I try to use RawConfigParser instead of ConfigParser.
